using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ExcelTool.Parser
{
    public static class GenAudioConsts
    {
        public static bool Gen(
            List<ParsedSheet> parsedSheets,
            List<ParsedEnum> enumSheets,
            string outputDir,
            string nameSpace = "")
        {
            try
            {
                ParsedSheet audioSheet = parsedSheets?.Find(s => s.SheetName == "AudioObject");
                bool hasAudioObject = audioSheet != null;
                bool hasEnums       = enumSheets is { Count: > 0 };

                if (!hasAudioObject && !hasEnums) return true;

                // 根据是否有 namespace 决定顶层缩进
                string i1 = string.IsNullOrEmpty(nameSpace) ? "" : "\t";   // class 级
                string i2 = i1 + "\t";                                      // class 成员级
                string i3 = i2 + "\t";                                      // 嵌套 class 成员级

                StringBuilder sb = new();
                sb.Append("/*\n * auto generated by tools(注意:千万不要手动修改本文件)\n * AudioConsts\n */\n\n");
                sb.Append("using System.Collections.Generic;\nusing System.Diagnostics.CodeAnalysis;\n\n");

                if (!string.IsNullOrEmpty(nameSpace))
                    sb.Append($"namespace {nameSpace}\n{{\n");

                // ── CUES ──────────────────────────────────────────────────────────
                if (hasAudioObject)
                {
                    AppendCues(sb, audioSheet, i1, i2);
                    sb.Append('\n');
                }

                // ── NAME_DICTIONARIES ─────────────────────────────────────────────
                if (hasAudioObject)
                {
                    AppendNameDictionaries(sb, audioSheet, i1, i2, i3);
                    sb.Append('\n');
                }

                // ── PARAMETERS ────────────────────────────────────────────────────
                if (hasEnums)
                {
                    AppendParameters(sb, enumSheets, i1, i2, i3);
                }

                if (!string.IsNullOrEmpty(nameSpace))
                    sb.Append("}\n");

                FileManager.WriteToFile(Path.Combine(outputDir, "AudioConsts.cs"), sb.ToString());
                return true;
            }
            catch (Exception ex)
            {
                ex.ToString().WriteErrorLine();
                return false;
            }
        }

        // ──────────────────────────────────────────────────────────────────────────
        //  CUES
        // ──────────────────────────────────────────────────────────────────────────

        private static void AppendCues(StringBuilder sb, ParsedSheet audioSheet, string i1, string i2)
        {
            int idIndex = audioSheet.Headers.FindIndex(h => h.FieldName == "Id");
            int cueNameIndex = audioSheet.Headers.FindIndex(h => h.FieldName == "CueName");

            // 如果没有 CueName 字段，回退到 Name 字段（向后兼容）
            if (cueNameIndex < 0)
            {
                cueNameIndex = audioSheet.Headers.FindIndex(h => h.FieldName == "Name");
                if (cueNameIndex < 0)
                {
                    // 两个字段都没有，跳过 CUES 生成
                    sb.Append($"{i1}public class Cues\n{i1}{{\n");
                    sb.Append($"{i1}}} //public class Cues\n");
                    return;
                }
            }

            Dictionary<string, uint> cueNameToMinId = BuildNameToMinId(audioSheet, idIndex, cueNameIndex);

            sb.AppendLine($"{i1}[SuppressMessage(\"ReSharper\", \"InconsistentNaming\")]");
            sb.Append($"{i1}public class Cues\n{i1}{{\n");
            foreach (KeyValuePair<string, uint> kv in cueNameToMinId)
            {
                string fieldName = SanitizeIdentifier(kv.Key);
                sb.Append($"{i2}public static uint {fieldName} = {kv.Value};\n");
            }
            sb.Append($"{i1}}} //public class Cues\n");
        }

        // ──────────────────────────────────────────────────────────────────────────
        //  NAME_DICTIONARIES
        // ──────────────────────────────────────────────────────────────────────────

        private static void AppendNameDictionaries(
            StringBuilder sb, ParsedSheet audioSheet,
            string i1, string i2, string i3)
        {
            int idIndex    = audioSheet.Headers.FindIndex(h => h.FieldName == "Id");
            int namesIndex = audioSheet.Headers.FindIndex(h => h.FieldName == "Name");

            Dictionary<uint, List<string>> idToNames = new();
            Dictionary<string, List<uint>> nameToIds = new();

            foreach (TableExcelRow row in audioSheet.Data.Rows)
            {
                if (idIndex < 0 || namesIndex < 0) continue;
                if (string.IsNullOrEmpty(row.StrList[idIndex])) continue;

                uint id = Convert.ToUInt32(row.StrList[idIndex]);
                if (id == 0) continue;  // 跳过ID=0的行
                
                string rawNames = row.StrList[namesIndex];
                List<string> names = new(rawNames.Split(['|'], StringSplitOptions.RemoveEmptyEntries));

                idToNames[id] = names;
                foreach (string name in names)
                {
                    if (!nameToIds.TryGetValue(name, out List<uint> list))
                    {
                        list = [];
                        nameToIds[name] = list;
                    }
                    list.Add(id);
                }
            }

            sb.AppendLine($"{i1}[SuppressMessage(\"ReSharper\", \"ClassNeverInstantiated.Global\")]");
            sb.Append($"{i1}public class NameDictionaries\n{i1}{{\n");

            // NameToId
            sb.Append($"{i2}public static readonly Dictionary<string, uint> NameToId = new()\n{i2}{{\n");
            foreach (var kv in nameToIds)
            {
                uint minId = uint.MaxValue;
                foreach (uint id in kv.Value)
                    if (id < minId) minId = id;
                sb.Append($"{i3}{{ \"{kv.Key}\", {minId} }},\n");
            }
            sb.Append($"{i2}}};\n\n");

            // AmbiguousNames
            sb.Append($"{i2}public static readonly HashSet<string> AmbiguousNames = new()\n{i2}{{\n");
            foreach (var kv in nameToIds)
                if (kv.Value.Count > 1)
                    sb.Append($"{i3}\"{kv.Key}\",\n");
            sb.Append($"{i2}}};\n\n");

            // SharedIdNames
            HashSet<string> sharedNames = [];
            foreach (var kv in idToNames)
                if (kv.Value.Count > 1)
                    foreach (string name in kv.Value)
                        sharedNames.Add(name);

            sb.Append($"{i2}public static readonly HashSet<string> SharedIdNames = new()\n{i2}{{\n");
            foreach (string name in sharedNames)
                sb.Append($"{i3}\"{name}\",\n");
            sb.Append($"{i2}}};\n");

            sb.Append($"{i1}}} //public class NameDictionaries\n");
        }

        // ──────────────────────────────────────────────────────────────────────────
        //  PARAMETERS
        // ──────────────────────────────────────────────────────────────────────────

        private static void AppendParameters(
            StringBuilder sb, List<ParsedEnum> enumSheets,
            string i1, string i2, string i3)
        {
            sb.AppendLine($"{i1}[SuppressMessage(\"ReSharper\", \"ClassNeverInstantiated.Global\")]");
            sb.Append($"{i1}public class Parameters\n{i1}{{\n");

            // EnumIds 嵌套静态类
            sb.Append($"{i2}public static class EnumIds\n{i2}{{\n");
            foreach (ParsedEnum parsedEnum in enumSheets)
                sb.Append($"{i3}public const uint {parsedEnum.EnumName}Id = {parsedEnum.Id};\n\n");

            sb.Append($"\n{i3}public static void RegisterAllGameState()\n{i3}{{\n");
            foreach (ParsedEnum parsedEnum in enumSheets)
                sb.Append($"{i3}\tStateGroupRegistry.Register<{parsedEnum.EnumName}>({parsedEnum.Id});\n");
            sb.Append($"{i3}}}\n");
            sb.Append($"{i2}}}\n\n");

            // enum 定义
            foreach (ParsedEnum parsedEnum in enumSheets)
            {
                sb.Append($"{i2}public enum {parsedEnum.EnumName}\n{i2}{{\n");
                foreach (ParsedEnumMember member in parsedEnum.Members)
                {
                    string valuePart = member.Value.HasValue ? $" = {member.Value.Value}" : "";
                    string descPart  = string.IsNullOrEmpty(member.Desc) ? "" : $" // {member.Desc}";
                    sb.Append($"{i3}{member.Key}{valuePart},{descPart}\n");
                }
                sb.Append($"{i2}}}\n\n");
            }

            sb.Append($"{i1}}} //public class Parameters\n");
        }

        // ──────────────────────────────────────────────────────────────────────────
        //  工具方法
        // ──────────────────────────────────────────────────────────────────────────

        /// <summary>遍历 AudioObject 行，构建 name -> minId 映射（处理资源复用）</summary>
        private static Dictionary<string, uint> BuildNameToMinId(
            ParsedSheet audioSheet, int idIndex, int namesIndex)
        {
            Dictionary<string, List<uint>> nameToIds = new();
            foreach (TableExcelRow row in audioSheet.Data.Rows)
            {
                if (idIndex < 0 || namesIndex < 0) continue;
                if (string.IsNullOrEmpty(row.StrList[idIndex])) continue;

                uint id = Convert.ToUInt32(row.StrList[idIndex]);
                if (id == 0) continue;  // 跳过ID=0的行

                string rawNames = row.StrList[namesIndex];
                List<string> names = new(rawNames.Split(['|'], StringSplitOptions.RemoveEmptyEntries));

                foreach (string name in names)
                {
                    if (!nameToIds.TryGetValue(name, out List<uint> list))
                    {
                        list = [];
                        nameToIds[name] = list;
                    }
                    list.Add(id);
                }
            }

            Dictionary<string, uint> result = new();
            foreach (var kv in nameToIds)
            {
                uint minId = uint.MaxValue;
                foreach (uint id in kv.Value)
                    if (id < minId) minId = id;
                result[kv.Key] = minId;
            }
            return result;
        }

        /// <summary>将字符串中不合法的 C# 标识符字符替换为下划线</summary>
        private static string SanitizeIdentifier(string name)
        {
            StringBuilder sb = new();
            foreach (char c in name)
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            if (sb.Length > 0 && char.IsDigit(sb[0]))
                sb.Insert(0, '_');
            return sb.ToString();
        }
    }
}
