using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ExcelTool.Parser
{
    public static class GenEnums
    {
        /// <summary>
        /// 所有枚举写入同一个文件 AudioEnums.cs
        /// </summary>
        public static bool GenCSharpEnum(List<ParsedEnum> enumSheet, string outputDir, string nameSpace = "")
        {
            try
            {
                StringBuilder sb = new();
                sb.Append("/*\n * auto generated by tools(注意:千万不要手动修改本文件)\n * AudioEnums\n */\n\n");

                if (!string.IsNullOrEmpty(nameSpace))
                    sb.Append($"namespace {nameSpace}\n{{\n");

                foreach (ParsedEnum parsedEnum in enumSheet)
                {
                    sb.Append($"\tpublic enum {parsedEnum.EnumName}\n\t{{\n");

                    foreach (ParsedEnumMember member in parsedEnum.Members)
                    {
                        string valuePart = member.Value.HasValue ? $" = {member.Value.Value}" : "";
                        string descPart  = string.IsNullOrEmpty(member.Desc) ? "" : $" // {member.Desc}";
                        sb.Append($"\t\t{member.Key}{valuePart},{descPart}\n");
                    }

                    sb.Append("\t}\n\n");
                }

                if (!string.IsNullOrEmpty(nameSpace))
                    sb.Append("}\n");

                FileManager.WriteToFile(Path.Combine(outputDir, "AudioEnums.cs"), sb.ToString());
                return true;
            }
            catch (Exception ex)
            {
                ex.ToString().WriteErrorLine();
                return false;
            }
        }

        /// <summary>
        /// 将所有枚举的 Id 汇总，生成 EnumIds.cs 静态常量类
        /// </summary>
        public static bool GenEnumIds(List<ParsedEnum> enumSheet, string outputDir, string nameSpace = "")
        {
            try
            {
                StringBuilder sb = new();
                sb.Append("/*\n * auto generated by tools(注意:千万不要手动修改本文件)\n * EnumIds\n */\n\n");

                if (!string.IsNullOrEmpty(nameSpace))
                    sb.Append($"namespace {nameSpace}\n{{\n");

                sb.Append("\tpublic static class EnumIds\n\t{\n");

                foreach (ParsedEnum parsedEnum in enumSheet)
                    sb.AppendLine($"\t\tpublic const uint {parsedEnum.EnumName} = {parsedEnum.Id};\n");

                sb.AppendLine("\t\tpublic static void RegisterAllGameState()\n\t\t{");
                foreach (ParsedEnum parsedEnum in enumSheet)
                {
                    sb.AppendLine($"\t\t\tStateGroupRegistry.Register<{parsedEnum.EnumName}>({parsedEnum.Id});");
                }
                sb.AppendLine("\t\t}");

                sb.Append("\t}\n");


                if (!string.IsNullOrEmpty(nameSpace))
                    sb.Append("}\n");

                FileManager.WriteToFile(Path.Combine(outputDir, "AudioEnumIds.cs"), sb.ToString());
                return true;
            }
            catch (Exception ex)
            {
                ex.ToString().WriteErrorLine();
                return false;
            }
        }
    }
}
